from __future__ import annotations

import hashlib
import pathlib
import sys


def as_cpp_bytes(data: bytes) -> str:
    return ", ".join(f"0x{byte:02x}" for byte in data)


def escape_cpp_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    if len(sys.argv) < 4 or (len(sys.argv) - 3) % 2 != 0:
        print("usage: generate_web_assets.py <header> <source> <path> <name> [...]", file=sys.stderr)
        return 1

    header_path = pathlib.Path(sys.argv[1])
    source_path = pathlib.Path(sys.argv[2])
    pairs = list(zip(sys.argv[3::2], sys.argv[4::2]))

    assets: list[dict[str, object]] = []
    digest = hashlib.sha256()
    for file_name, symbol_name in pairs:
        file_path = pathlib.Path(file_name)
        data = file_path.read_bytes()
        digest.update(file_path.name.encode("utf-8"))
        digest.update(data)
        assets.append(
            {
                "file_name": file_path.name,
                "symbol_name": symbol_name,
                "size": len(data),
                "bytes": as_cpp_bytes(data),
            }
        )

    version = digest.hexdigest()[:16]

    header = f"""/*
 * Auto-generated by generate_web_assets.py
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef FAN_CONTROLLER_GENERATED_WEB_ASSETS_HPP_
#define FAN_CONTROLLER_GENERATED_WEB_ASSETS_HPP_

#include <stddef.h>
#include <stdint.h>

namespace fanctl::storage {{

struct WebAsset {{
    const char *path;
    const uint8_t *data;
    size_t size;
}};

extern const char *const kWebAssetsVersion;
extern const WebAsset kWebAssets[];
extern const size_t kWebAssetCount;

}} // namespace fanctl::storage

#endif
"""

    source_lines = [
        "/*",
        " * Auto-generated by generate_web_assets.py",
        " * SPDX-License-Identifier: Apache-2.0",
        " */",
        "",
        '#include "generated/web_assets.hpp"',
        "",
        "namespace fanctl::storage {",
        "",
        f'const char *const kWebAssetsVersion = "{version}";',
        "",
    ]

    for asset in assets:
        source_lines.append(
            f'static const uint8_t {asset["symbol_name"]}[] = {{ {asset["bytes"]} }};'
        )

    source_lines.extend(
        [
            "",
            "const WebAsset kWebAssets[] = {",
        ]
    )

    for asset in assets:
        source_lines.append(
            f'    {{ "/srv/www/{escape_cpp_string(asset["file_name"])}", {asset["symbol_name"]}, {asset["size"]} }},'
        )

    source_lines.extend(
        [
            "};",
            "",
            "const size_t kWebAssetCount = sizeof(kWebAssets) / sizeof(kWebAssets[0]);",
            "",
            "} // namespace fanctl::storage",
            "",
        ]
    )

    header_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(header, encoding="utf-8")
    source_path.write_text("\n".join(source_lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
